import 'package:json_annotation/json_annotation.dart';

enum Platform {
  pc,
  playstation5,
  playstation4,
  playstation3,
  playstation2,
  playstation1,
  @JsonValue('xbox-one')
  xboxOne,
  @JsonValue('xbox-series-x')
  xboxSeriesX,
  @JsonValue('nintendo-switch')
  nintendoSwitch,
  @JsonValue('nintendo-64')
  nintendo64,
  ios,
  android,
  @JsonValue('nintendo-3ds')
  nintendo3ds,
  @JsonValue('nintendo-ds')
  nintendoDs,
  @JsonValue('nintendo-dsi')
  nintendoDsi,
  macos,
  linux,
  xbox360,
  @JsonValue('xbox-old')
  xboxOld,
  @JsonValue('ps-vita')
  psVita,
  psp,
  @JsonValue('wii-u')
  wiiU,
  wii,
  gamecube,
  @JsonValue('game-boy-advance')
  gameBoyAdvance,
  @JsonValue('game-boy-color')
  gameBoy,
  @JsonValue('game-boy')
  gameBoyColor,
  snes,
  nes,
  macintosh,
  @JsonValue('apple-ii')
  appleII,
  @JsonValue('commodore-amiga')
  commodoreAmiga,
  @JsonValue('atari-7800')
  atari7800,
  @JsonValue('atari-5200')
  atari5200,
  @JsonValue('atari-2600')
  atari2600,
  @JsonValue('atari-flashback')
  atariFlashback,
  @JsonValue('atari-8-bit')
  atari8Bit,
  @JsonValue('atari-st')
  atariST,
  @JsonValue('atari-lynx')
  atariLynx,
  @JsonValue('atari-xegs')
  atariXEGS,
  genesis,
  @JsonValue('sega-saturn')
  segaSaturn,
  @JsonValue('sega-cd')
  segaCD,
  @JsonValue('sega-32x')
  sega32x,
  @JsonValue('sega-master-system')
  segaMasterSystem,
  dreamcast,
  @JsonValue('3do')
  threeDO,
  jaguar,
  @JsonValue('game-gear')
  gameGear,
  neogeo,
  web,
}
